/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type DayImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "dayImage.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type PostReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'post'
}

export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type ContentEditor = {
  _type: 'contentEditor'
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'blockquote' | 'hr' | 'h1' | 'h2' | 'h3' | 'h4'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | {
              href?: string
              _type: 'link'
              _key: string
            }
          | {
              reference?: PostReference
              _type: 'internalLink'
              _key: string
            }
          | {
              refId?: string
              _type: 'cite'
              _key: string
            }
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        caption?: string
        dayImage?: DayImage
        smallMargin?: boolean
        duotone?: boolean
        largeView?: boolean
        _type: 'image'
        _key: string
      }
    | {
        url: string
        aspectRatio?: '16/9' | '4/3' | '1/1' | '9/16'
        caption?: string
        smallMargin?: boolean
        largeView?: boolean
        _type: 'iframe'
        _key: string
      }
    | {
        asset?: SanityFileAssetReference
        media?: unknown
        caption?: string
        autoplay?: boolean
        flashWarning?: boolean
        smallMargin?: boolean
        largeView?: boolean
        _type: 'video'
        _key: string
      }
    | {
        heading?: string
        subheading?: string
        collapsed?: boolean
        lines?: Array<{
          label?: string
          value?: string
          _type: 'line'
          _key: string
        }>
        _type: 'transcript'
        _key: string
      }
    | {
        heading?: string
        subheading?: string
        header?: Array<string>
        rows?: Array<{
          cells?: Array<string>
          _type: 'row'
          _key: string
        }>
        caption?: string
        _type: 'table'
        _key: string
      }
    | {
        chartType: 'line' | 'histogram'
        data: string
        xLabel?: string
        yLabel?: string
        caption?: string
        _type: 'chart'
        _key: string
      }
    | {
        content?: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'normal'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<
            | {
                href?: string
                _type: 'link'
                _key: string
              }
            | {
                reference?: PostReference
                _type: 'internalLink'
                _key: string
              }
            | {
                refId?: string
                _type: 'cite'
                _key: string
              }
          >
          level?: number
          _type: 'block'
          _key: string
        }>
        _type: 'abstract'
        _key: string
      }
    | {
        summary: string
        content?: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'normal' | 'blockquote' | 'hr' | 'h1' | 'h2' | 'h3' | 'h4'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<
                | {
                    href?: string
                    _type: 'link'
                    _key: string
                  }
                | {
                    reference?: PostReference
                    _type: 'internalLink'
                    _key: string
                  }
                | {
                    refId?: string
                    _type: 'cite'
                    _key: string
                  }
              >
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              caption?: string
              dayImage?: DayImage
              smallMargin?: boolean
              duotone?: boolean
              largeView?: boolean
              _type: 'image'
              _key: string
            }
          | {
              url: string
              aspectRatio?: '16/9' | '4/3' | '1/1' | '9/16'
              caption?: string
              smallMargin?: boolean
              largeView?: boolean
              _type: 'iframe'
              _key: string
            }
          | {
              asset?: SanityFileAssetReference
              media?: unknown
              caption?: string
              autoplay?: boolean
              flashWarning?: boolean
              smallMargin?: boolean
              largeView?: boolean
              _type: 'video'
              _key: string
            }
          | {
              heading?: string
              subheading?: string
              collapsed?: boolean
              lines?: Array<{
                label?: string
                value?: string
                _type: 'line'
                _key: string
              }>
              _type: 'transcript'
              _key: string
            }
          | {
              heading?: string
              subheading?: string
              header?: Array<string>
              rows?: Array<{
                cells?: Array<string>
                _type: 'row'
                _key: string
              }>
              caption?: string
              _type: 'table'
              _key: string
            }
          | {
              chartType: 'line' | 'histogram'
              data: string
              xLabel?: string
              yLabel?: string
              caption?: string
              _type: 'chart'
              _key: string
            }
        >
        _type: 'details'
        _key: string
      }
  >
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  links?: Array<
    | {
        label: string
        url: string
        _type: 'navLink'
        _key: string
      }
    | {
        label: string
        reference: PostReference
        _type: 'navPostLink'
        _key: string
      }
  >
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  projectCode?: string
  authors?: Array<{
    name: string
    url?: string
    _type: 'author'
    _key: string
  }>
  date?: string
  metaDescription?: string
  externalLinks?: Array<{
    label: string
    url: string
    _type: 'externalLink'
    _key: string
  }>
  content?: ContentEditor
  showToc?: boolean
  toc?: Array<{
    index?: string
    label: string
    anchor: string
    _type: 'tocEntry'
    _key: string
  }>
  references?: Array<{
    id: string
    label: string
    year: string
    text: string
    url?: string
    _type: 'refItem'
    _key: string
  }>
  featuredImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    caption?: string
    attribution?: string
    _type: 'image'
  }
  slug: Slug
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Frontpage = {
  _id: string
  _type: 'frontpage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  posts?: Array<
    {
      _key: string
    } & PostReference
  >
}

export type MuxVideoAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'mux.videoAsset'
}

export type MuxVideo = {
  _type: 'mux.video'
  asset?: MuxVideoAssetReference
}

export type MuxVideoAsset = {
  _id: string
  _type: 'mux.videoAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  status?: string
  assetId?: string
  playbackId?: string
  filename?: string
  thumbTime?: number
  data?: MuxAssetData
}

export type MuxAssetData = {
  _type: 'mux.assetData'
  resolution_tier?: string
  upload_id?: string
  created_at?: string
  id?: string
  status?: string
  max_stored_resolution?: string
  passthrough?: string
  encoding_tier?: string
  video_quality?: string
  master_access?: string
  aspect_ratio?: string
  duration?: number
  max_stored_frame_rate?: number
  mp4_support?: string
  max_resolution_tier?: string
  tracks?: Array<
    {
      _key: string
    } & MuxTrack
  >
  playback_ids?: Array<
    {
      _key: string
    } & MuxPlaybackId
  >
  static_renditions?: MuxStaticRenditions
  master?: MuxMasterFile
}

export type MuxMasterFile = {
  _type: 'mux.masterFile'
  status?: string
  url?: string
}

export type MuxStaticRenditions = {
  _type: 'mux.staticRenditions'
  status?: string
  files?: Array<
    {
      _key: string
    } & MuxStaticRenditionFile
  >
}

export type MuxStaticRenditionFile = {
  _type: 'mux.staticRenditionFile'
  name?: string
  ext?: string
  height?: number
  width?: number
  bitrate?: number
  filesize?: string
  type?: string
  status?: string
  resolution_tier?: string
  resolution?: string
  id?: string
  passthrough?: string
}

export type MuxPlaybackId = {
  _type: 'mux.playbackId'
  id?: string
  policy?: string
}

export type MuxTrack = {
  _type: 'mux.track'
  id?: string
  type?: string
  max_width?: number
  max_frame_rate?: number
  duration?: number
  max_height?: number
  language_code?: string
  name?: string
  status?: string
  text_source?: string
  text_type?: string
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | DayImage
  | PostReference
  | SanityFileAssetReference
  | ContentEditor
  | SiteSettings
  | Post
  | Slug
  | SanityImageCrop
  | SanityImageHotspot
  | Frontpage
  | MuxVideoAssetReference
  | MuxVideo
  | MuxVideoAsset
  | MuxAssetData
  | MuxMasterFile
  | MuxStaticRenditions
  | MuxStaticRenditionFile
  | MuxPlaybackId
  | MuxTrack
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
